version: "3"
services:
  chatpad:
    image: expd-chatpad:latest
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ${FAVICON}:/usr/share/nginx/html/favicon.8c9f2c75.png
      - ${COMPANY_LOGO_DARK}:/usr/share/nginx/html/logo-dark.0c614d67.svg
      - ${COMPANY_LOGO_LIGHT}:/usr/share/nginx/html/logo-light.9995db93.svg
      - ${COMPANY_LOGO_MINIMAL_DARK}:/usr/share/nginx/html/logo-minimal-dark.9b737d7e.svg
      - ${COMPANY_LOGO_MINIMAL_LIGHT}:/usr/share/nginx/html/logo-minimal-light.d90eabe4.svg
  configserver:
    image: halverneus/static-file-server:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - FOLDER=/chatpad
      - CORS=true
    volumes:
      - ${CONFIG_PATH}:/chatpad/config.json